// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgkvjozxglnrgpedbnag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impna3Zqb3p4Z2xucmdwZWRibmFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzMzMTUsImV4cCI6MjA2NTUwOTMxNX0.lQdfblqxWH-VZB-9TB_ufOG5fNFlLztikRNWkyLh4sc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);